# Generated by Django 4.2.1 on 2023-06-03 18:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('fullname', models.CharField(blank=True, max_length=100, null=True)),
                ('home_lat', models.FloatField(blank=True, null=True)),
                ('home_lng', models.FloatField(blank=True, null=True)),
                ('license', models.CharField(max_length=200)),
                ('image', models.URLField(blank=True, null=True, validators=[django.core.validators.URLValidator()])),
                ('dri_created', models.DateTimeField(auto_now_add=True)),
                ('dri_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('enable_loc', models.BooleanField(default=False)),
                ('frequently_visited', models.CharField(max_length=200)),
                ('use_created', models.DateTimeField(auto_now_add=True)),
                ('use_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('current_loc_lat', models.FloatField(blank=True, null=True)),
                ('current_loc_lng', models.FloatField(blank=True, null=True)),
                ('home_loc_lat', models.FloatField(blank=True, null=True)),
                ('home_loc_lng', models.FloatField(blank=True, null=True)),
                ('pas_created', models.DateTimeField(auto_now_add=True)),
                ('pas_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('pas_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seeme.user')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('loc_name', models.CharField(blank=True, max_length=255, null=True)),
                ('loc_latitude', models.FloatField(blank=True, null=True)),
                ('loc_longitude', models.FloatField(blank=True, null=True)),
                ('loc_created', models.DateTimeField(auto_now_add=True)),
                ('loc_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('driver', models.ManyToManyField(blank=True, to='seeme.driver')),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='dri_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seeme.user'),
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('des_name', models.CharField(blank=True, max_length=255, null=True)),
                ('des_latitude', models.FloatField(blank=True, null=True)),
                ('des_longitude', models.FloatField(blank=True, null=True)),
                ('des_created', models.DateTimeField(auto_now_add=True)),
                ('des_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeme.passenger')),
            ],
        ),
    ]
