# Generated by Django 4.2.2 on 2023-06-16 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeme', '0002_alter_destination_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='passenger',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='seeme.user'),
        ),
    ]
