# Generated by Django 4.2.2 on 2023-06-15 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seeme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='passenger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seeme.user'),
        ),
    ]
